# Generated by Django 3.1.7 on 2021-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_by', models.CharField(default='', max_length=255)),
                ('post', models.CharField(default='', max_length=255)),
                ('testimonial_string', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(default='', upload_to='assets/images')),
            ],
        ),
    ]
