# Generated by Django 3.1.7 on 2021-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210406_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.CharField(default='', max_length=255)),
                ('advisor_post', models.CharField(default='', max_length=255)),
                ('advisor_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
