# Generated by Django 3.1.7 on 2021-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='background_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
